In [1]:
#import scipy.optimize
import numpy as np
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier



In [24]:
class CustomModelClassifier:
  def __init__(self, rfc, svclass):
    self.rfc = rfc
    self.SVClass  = svclass 
    return

  def train(self,X_train,y_train):
    self.rfc.fit(X_train,y_train)
    X_svc_train = self.fetchIndVectors(X_train)
    print(X_svc_train)
    nsamples, nx, ny = X_svc_train.shape
    X_svc_train =  X_svc_train.reshape((nsamples,nx*ny))
    self.SVClass.fit(X_svc_train,y_train)
    return

  def test(self,x_test):
    fi = self.fetchIndVectors(x_test)
    return self.SVClass.predict(fi)

  def fetchIndVectors(self,x_train):
    trees = self.rfc.estimators_
    yProb = list()
    for tree in trees:
        yProb.append([self.binarize(x) for x in tree.predict_proba(x_train)])
    yProb = np.array(yProb)    
    return yProb

  def binarize(self,vec):
    maxVal = max(vec)
    flag = 0
    for idx in range(len(vec)):
      val = vec[idx]
      if val < maxVal and val != 0:
        vec[idx] = 0
      elif flag == 0:
        vec[idx] = 1
        flag = 1
      else:
        vec[idx] = 0
    return vec





'''
def hinge_loss(t,y):
  #def max(0,1-t*y)
  return [max(0,1-t_i*y_i) for t_i,y_i in zip(t,y)]

def error_f(W,c_n,t_mat,y_mat):
  
  return (1/2) * (sqrt(np.matmul(np.transpose(W),W))) + c_n* sum(hinge_loss(t_mat,y_mat))
''' 

'\ndef hinge_loss(t,y):\n  #def max(0,1-t*y)\n  return [max(0,1-t_i*y_i) for t_i,y_i in zip(t,y)]\n\ndef error_f(W,c_n,t_mat,y_mat):\n  \n  return (1/2) * (sqrt(np.matmul(np.transpose(W),W))) + c_n* sum(hinge_loss(t_mat,y_mat))\n'



*   Podaci: usps
*   Tip: klasifikacija 



In [4]:
import h5py

#USPS data importing
path = "sample_data/usps.h5"
with h5py.File(path, 'r') as hf:
        train_usps = hf.get('train')
        X_tr_usps = train_usps.get('data')[:]
        y_tr_usps = train_usps.get('target')[:]
        test_usps = hf.get('test')
        X_te_usps = test_usps.get('data')[:]
        y_te_usps = test_usps.get('target')[:]

    


In [25]:



#number of tress = 100
#num of rand features tested in each node = sqrt of the feature dimension
#max tree depth 10,15 25
#min sample number for split is set to 5
#datasets without standard split ration is 60:40 train/test
#we report mean error and std every 10 rounds of experiment

depths = (10,15,25)
#check the depth
#check bootstraping(bootstrap variable) and random_state variable and oob_score

mdl_rfc = RandomForestClassifier(max_depth = 10, n_estimators = 100,min_samples_split = 5,max_features = "sqrt")
mdl_svc = SVC()
cm_model = CustomModelClassifier(mdl_rfc,mdl_svc)

cm_model.train(X_tr_usps,y_tr_usps)




[[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]]


ValueError: ignored